### ISSUE TITLE
release to marketplace

### ISSUE THREAD

**Issue by gorkem** [gorkem/vscode-java#1]
_From @maxandersen on July 6, 2016 14:59_

_Copied from original issue: gorkem/java-language-server#27_

**Comment by gorkem** [comment]
_From @egamma on July 14, 2016 8:30_

One thing to keep in mind is that the market place has a maximum size of 20MB for an extension. Since this extension will include a subset of eclipse, the extension will exceed this limit. 

One way to achieve this is that the extension downloads the eclipse bits on first activation of the extension. This is also how it is done by the vscode-omnisharp extension. 

Please see: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharp/serverLauncher.ts

@gorkem fyi

**Comment by gorkem** [comment]
@egamma Thanks for the heads up. I did not notice the limitation.

**Comment by neilsustc** [comment]
Looking forward to it :smile:

**Comment by gorkem** [comment]
Released at https://marketplace.visualstudio.com/items?itemName=redhat.java
