### ISSUE TITLE
Download requirement fails (with http error 503)

### ISSUE THREAD

**Issue by pcmind** [gorkem/vscode-java#11]
I am using VSC behind a proxy and plugin is not able to download dependencies.

It fails because [Server Url](http://download.jboss.org/jbosstools/static/vscode/java-server-1.0.0-201609122022.tar.gz) is a http, and downloadManager use https agent without setting the `options.port ` to the correct port. 
[agent-base](https://github.com/TooTallNate/node-agent-base/blob/12a9a851006bd039a0340fa876916266847a6044/patch-core.js#L50) set port to 443, when `options.port ` is omitted. Request fail because resource is unavailable at this new location.

**Comment by gorkem** [comment]
just pushed 0.0.2 to marketplace. It now uses https download urls
