### ISSUE TITLE
Javadoc formatting needs some love

### ISSUE THREAD

**Issue by fbricon** [gorkem/vscode-java#13]
There's a lot of empty spaces
![javadoc-formatting](https://cloud.githubusercontent.com/assets/148698/18530912/9c331814-7aa1-11e6-84f8-5820b15a0953.png)

Seems hyperlinks are not rendered either

**Comment by gorkem** [comment]
partially related to https://github.com/gorkem/java-language-server/issues/5 
the hyprelinks needs to be converted to markdown.

**Comment by fbricon** [comment]
Formatting is [fixed](https://github.com/Microsoft/vscode/issues/2330) in VS Code, upstream. You can test it in a [VS Code insider build](https://code.visualstudio.com/insiders) (i.e nightly build). There should be a new VS Code release next month.

<img width="476" alt="javadoc" src="https://cloud.githubusercontent.com/assets/148698/18797360/9f896436-819b-11e6-8547-5048a38efece.png">

HTML links are now properly rendered (but not `{@link}` yet, this will require extra work)
![links-javadoc](https://cloud.githubusercontent.com/assets/148698/18797704/27f9447a-819d-11e6-9d94-eb2f425f9564.png)
