### ISSUE TITLE
Provide syntax coloring for opened *.class files

### ISSUE THREAD

**Issue by fbricon** [gorkem/vscode-java#21]
When opening a reference from a source jar, the associated .class file opens with the default editor. It should use the java coloring scheme instead

**Comment by gorkem** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8n1pTFY9&#x2F;218-update-thym-version-to-2-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> update Thym version to 2.1</a>
