### ISSUE TITLE
Go to Definition (F12) opens the .class file, however there is no syntax highlighting?

### ISSUE THREAD

**Issue by StefH** [gorkem/vscode-java#24]
No syntax highlighting for `.class` files?
![2016-09-19_10h33_50](https://cloud.githubusercontent.com/assets/249938/18626317/90d37322-7e54-11e6-8c4d-1a6eafb158ae.png)

Should I install another extension for this ?

**Comment by fbricon** [comment]
Already fixed in #21. We're planning a new release before the end of the month.

**Comment by fbricon** [comment]
Until the release, you can add a `".class" -> "java"` association to vs code settings following the instructions in https://scottaddie.com/2016/04/10/file-to-language-associations-in-visual-studio-code/
