### ISSUE TITLE
Expose server JVM launch parameters

### ISSUE THREAD

**Issue by fbricon** [gorkem/vscode-java#25]
We should make it possible for users to override the default JVM launch parameters for the server.
Typically, users should be able to increase the amount of memory  of the JVM or launch the server with some java agents (eg. lombok, as requested on https://marketplace.visualstudio.com/items?itemName=redhat.java)

**Comment by fbricon** [comment]
See https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration for info about contributing settings

**Comment by gorkem** [comment]
What should we do if the JVM parameters change for a running server?

**Comment by fbricon** [comment]
Detect the change, restart the server? Worst case scenario, display a warning asking the user to restart
