### ISSUE TITLE
Option to specify Java path ?

### ISSUE THREAD

**Issue by warpdesign** [gorkem/vscode-java#28]
The extension needs Java 8 and I'm working on Java 7 projects so I cannot updated to Java 8 easily.

How about an option to specify Java directory (JAVA_HOME already points to Java 7) ?

**Comment by gorkem** [comment]
Yes, probably a configuration to tell the extension to use a different JVM than the system one.

**Comment by fbricon** [comment]
Using, as long as you're using Maven, the pom.xml settings will configure source and target compilation level appropriately even if running on JDK 8.

However, I reckon it'd be good to be able to compile projects with an actual JDK 7 (or 5,6 or 9) to prevent classes from using the wrong API (i.e. leaking JDK 8 API, like String:isEmpty(), but targeting JDK7).

So I think we actually need 2 levels of settings:
- setting the JVM running the JLS
- setting available JDKs available for actual project compilation

**Comment by ianrobrien** [comment]
I have a Java 8 JRE on my System and User path but the extension does not recognize it.

**Comment by gorkem** [comment]
@ianrobrien what is the OS?

**Comment by ianrobrien** [comment]
Windows 7 Enterprise x64 SP1. From that quote I posted I couldn't tell if it was supposed to search the path first AND then JAVA_HOME, or if Java 8 needed to be set for both values.

**Comment by DDErasmus** [comment]
I have the same issue, in that the jre is not being detected.
Window 10 64bit with jre 1.8.0.101
jre is in the path & JAVA_HOME is set
![image](https://cloud.githubusercontent.com/assets/20951649/18750006/3c1afe52-80d1-11e6-8548-3db1690a20c8.png)

![image](https://cloud.githubusercontent.com/assets/20951649/18750033/58542c24-80d1-11e6-9fb6-d0fbd35387ff.png)

**Comment by ianrobrien** [comment]
I also tried adding the JDK and JRE to both paths (user and system) and both the top level directories and the bin directories. I can try some more options, but I pretty much need to keep JAVA_HOME pointed to a 1.6 installation.

**Comment by DDErasmus** [comment]
Changing to JDK worked for me too - I guess the documentation should be updated as it specifies that it requires a "Java 8 Runtime" not a Java 8 Development Kit.

**Comment by gorkem** [comment]
Changed references to JRE https://github.com/gorkem/vscode-java/commit/395d61bf25eccc5a505bccf1c1b70d3066503206

**Comment by fbricon** [comment]
The error message is now a bit more explicit:
![](http://content.screencast.com/users/fbricon/folders/Jing/media/9c531f13-934e-4119-b483-fb481031e600/00000468.png)

**Comment by amitmerin** [comment]
On mac, I get the same "java language support requires java 8 to run vscode.." error as mentioned above.
![screen shot 2016-09-23 at 5 28 11 pm](https://cloud.githubusercontent.com/assets/13625738/18801836/31223c1c-81b3-11e6-8005-195c6be31c72.png)

JAVA_HOME seems to point to the write place...
/usr/libexec/java_home -V
Matching Java Virtual Machines (1):
    1.8.0_101, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home

**Comment by gorkem** [comment]
I think we should introduce a single configuration that points to the Java SDK used for running the JLS. This configuration can take precedence over _JAVA_HOME_, freeing _JAVA_HOME_ to point to the Java SDK used for compilation of the project. We just need to make sure that the JLS always uses the SDK at _JAVA_HOME_  as part of the build path. If _JAVA_HOME_ is not set it can fall back to the SDK that is running the JLS.

How about _java.home_ as the configuration?

**Comment by fbricon** [comment]
Current PR adds the `java.home` property:

<img width="1247" alt="capture d ecran 2016-09-26 a 17 50 38" src="https://cloud.githubusercontent.com/assets/148698/18853245/1d3a61b4-8412-11e6-8c3f-16df8eb7fca2.png">

However, VS Code needs to be restarted after setting the value. I'll see if we can just restart the JLS instead, when a change in the property is detected

**Comment by luolong** [comment]
Just a note. 

I'm on a macOS and I don't have JAVA_HOME environment variable set on my system. I only set it for tools on a command line shell when a specific Java version is required by setting it till the value of '/use/libexec/java_home'

**Comment by fbricon** [comment]
See https://github.com/gorkem/vscode-java#supported-settings

**Comment by mabellLU** [comment]
Ok, so I have a project that runs on Java 6. How do I get the project built in Java 6, but the plugin work in Java 8? I have both installed. I have java.home pointing to 8 to get the extension working, but my code doesn't compile.

**Comment by fbricon** [comment]
@mabellLU what kind of project is that? Maven? Gradle? Eclipse?

**Comment by mabellLU** [comment]
Gradle

**Comment by fbricon** [comment]
@mabellLU have you tried to set the target java version in your build.gradle?
```
compileJava {
  sourceCompatibility = 1.6
  targetCompatibility = 1.6
  ...
}
```
If that doesn't work, please open a new bug report with a sample project exhibiting the issue

**Comment by mabellLU** [comment]
yes have that, sorry we're using the play framework also, looks like there isn't support for scala?

**Comment by fbricon** [comment]
Sorry no, Scala support here.
We support all JVM languages as long as it's Java :-)

**Comment by optticall** [comment]
you can use -j to especify a version u wann use
